### ISSUE TITLE
REQUEST:- Random selection of Video Files

### ISSUE THREAD

**Issue by bigdant** [Snille/MMM-Videoplayer#2]
Hi,

Anyway to add a number of video files to play in a loop.

Or even better to add a number of video files into an array to play at random in a loop !!

Cheers

D.

**Comment by Snille** [comment]
Hi, I'm planning to do some enhancements to the module when I have some time. :) Thanks for the suggestions.

**Comment by Snille** [comment]
@bigdant Added some of your requests... :) I will make it a bit neater later on... But I hope it works ok now.
