### ISSUE TITLE
Play video files from a folder

### ISSUE THREAD

**Issue by Komufi** [Snille/MMM-Videoplayer#3]
Really enjoy this module! Thank you Snille
It is possible to play videos from a local folder where video files placed?

**Comment by Snille** [comment]
Good to hear! :) 
Yes, just add the files to the "local" video-folder:  "MMM-Videoplayer/video/"
Then add the following under the config part of the MMM-Videoplayer: 
`videolist: ["/modules/MMM-Videoplayer/video/yourvideo01.mp4", "/modules/MMM-Videoplayer/video/yourvideo02.mp4"]`
Just add more files as you want to the line remember the comma in between the files... :)
I hope that works... :)

**Comment by Cheese041** [comment]
Is it possible to play videos from an external drive, like a usb stick?

**Comment by Snille** [comment]
Hi @Cheese041, well, sort of.. :) If you make sure that the USB-stick (or drive) is mounted somewhere in the MM:s modules folder. The videoplayer can play files from anywhere inside the modules folders or from URL:s. So it's not as easy as to plug in a USB-stick and point to that folder (that would usually be /media/something (if you use Rasbian) but the MM modules can not access the files and folders outside the MM:s boundaries. (it's not allowed within the MM-system). So you have to mount the USB-stick (or drive) to somewhere in the MM:s modules folder... So, it can be done, but you have to do some "tricks". :)
Here is a guide for Rasbian: https://www.raspberrypi-spy.co.uk/2014/05/how-to-mount-a-usb-flash-disk-on-the-raspberry-pi/
But remember to create the "mount point" in step 3 to somewhere inside your MM:s modules folder (maybe do something like this: "/home/pi/MagicMirror/modules/MMM-Videoplayer/video/usb-stick" if you are using a RPi...) Then use that mount point in the rest of the guide... :) 

Then in the config in the videoplayer you would put:  video: "/modules/MMM-Videoplayer/video/usb-stick/your-movie.mp4",

**Comment by Cheese041** [comment]
It worked. Thank you so much!
