### ISSUE TITLE
Play files in the folder

### ISSUE THREAD

**Issue by zhanghaobb** [Snille/MMM-Videoplayer#5]
I am not sure if this is the right place to ask.
I wanted to play all the files in a directory, I can populate all files' path but seems like less automatic.
Is there a way to "auto" populate all files' path into videolist array?

thank you!

**Comment by Snille** [comment]
Hi, this video-player is not ment to do that. But there are other players that are. Look at the [3:d party list of modules](https://github.com/MichMich/MagicMirror/wiki/3rd-Party-Modules), I'm pretty sure you can find one that works the way you want. :)
