### ISSUE TITLE
No video is displayed when mirror is running

### ISSUE THREAD

**Issue by Precela** [Snille/MMM-Videoplayer#6]
Hello. I have installed the repository but the video is not displaying when i run it. 

I followed all the instructions and installed the MMM-Videoplayer in the ~MagicMirror/modules folder and added the config in config/config.js file. 
I changed the size of the file to see if the problem was with the size, but its still the same. 
![mm](https://user-images.githubusercontent.com/86070792/160617033-ab9ef661-18fd-4776-8e8c-951cd5ceb85b.JPG)
![image](https://user-images.githubusercontent.com/86070792/160617192-ba346604-42fe-4931-839f-c70ba3426add.png)
I added the module in the config file. 
![image](https://user-images.githubusercontent.com/86070792/160617401-f7b50cf8-0bf7-47f3-aee9-64cb84e64275.png)
I kept the CSS file as it is for now.
![image](https://user-images.githubusercontent.com/86070792/160617971-8a948598-65bf-4d06-b8b1-bc5a54a97138.png)

What am I doing wrong? Any help would be appreciated. Thank you.

**Comment by Snille** [comment]
Hi, it's hard to say. I can't see any "problems" from this, but is the video file present in that folder with the correct name? "/home/pi/MagicMirror/modules/MMM-Videoplayer/video/mov_bbb.mp4"?

**Comment by Precela** [comment]
yes the video file is present and the video works too. 
I will delete everything and try again to see if it works.

**Comment by Precela** [comment]
I am using Raspberrypi 3 model B+. Does this version support the module?

**Comment by Snille** [comment]
Hm... I have not tested it on a RPi, but you should at least se "something" I think. Even if the clip "stutters"... I have to do a "test install" on my development mirror to see if something is broke. I'll try to do that this weekend... :)

**Comment by Snille** [comment]
Just thought of something that may have to do with this, you have written the full (system) path to the video file. Try changing it to "/modules/MMM-Videoplayer/video/mov_bbb.mp4". The MM "root" is not the same as the "systems" root...

**Comment by Precela** [comment]
Yes it worked!! thank you so much.
